version: '3.8'
services:
  # server app
  app:
    image: nazmulhasn/sandrofp_app:latest
    container_name: sandrofp_app
    restart: always
    env_file:
      - .env
    environment:
      - REDIS_HOST=sandrofp_redis
      - REDIS_PORT=6379
      # - IP = 0.0.0.0
      # - PORT=6000
      # - SOCKET_PORT=6005
    ports:
      - '6000:6000'
      - '6005:6005'
      - '6136:6136'
    depends_on:
      - redis
    command: ['node', 'dist/server.js']

  # socket:
  #   image: nazmulhasn/sandrofp_socket:latest
  #   container_name: sandrofp_socket
  #   restart: always
  #   env_file:
  #     - .env
  #   ports:
  #     - "6005:6005"
  #   depends_on:
  #     - app
  #     - mongo
  #     - redis
  #   command: ["node", "dist/socket.js"]

  # mongo:
  #   image: mongo:6
  #   container_name: sandrofp_mongo
  #   ports:
  #     - '27017:27017'
  #   volumes:
  #     - mongo-data:/data/db
  #   restart: always

  #redis
  redis:
    image: redis:7.2-alpine
    container_name: sandrofp_redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    restart: always
    command: ['redis-server', '--appendonly', 'yes']

  postgres:
    image: postgres:15
    container_name: sandrofp_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: myapp_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - '5050:80'
    depends_on:
      - postgres
  # nginx:
  #   image: nginx:stable
  #   container_name: sandrofp_nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  #     - certbot-etc:/etc/letsencrypt
  #     - certbot-var:/var/lib/letsencrypt
  #     - ./public:/usr/share/nginx/html:ro
  #   depends_on:
  #     - app
  #     - socket

volumes:
  redis-data:
  postgres_data:
# volumes:
#   mongo-data:
#   certbot-etc:
#   certbot-var:
